config/routes.rb
Rails.application.routes.draw do

  resources :budgets

  resources :budgets do
    resources :expenses
    resources :incomes
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
end

app/models/budget.rb
class Budget < ActiveRecord::Base
	has_many :expenses, dependent: :destroy
	has_many :incomes, dependent: :destroy
	validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article
end

app/models/expense.rb
class Expense < ActiveRecord::Base
	validates :title, presence: true
	validates :value, presence: true, numericality: true
	validates :category, presence: true
	belongs_to :budget
end

app/models/income.rb
class Income < ActiveRecord::Base
	validates :title, presence: true
	validates :value, presence: true, numericality: true
	belongs_to :budget
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

	def index
		@budgets = Budget.all
	end

	def show
		@budget = Budget.find( params[ :id ] )
	end

	def new
		@budget = Budget.new
	end

	def edit
		@budget = Budget.find( params[ :id ] )
	end

	def create
		@budget = Budget.new( budget_params )

		if @budget.save
			redirect_to @budget
		else
			render 'new'
		end
	end

	def update
		@budget = Budget.find( params[ :id ] )

		if @budget.update( budget_params )
			redirect_to @budget
		else
			render 'edit'
		end
	end

	def destroy
		@budget = Budget.find( params[ :id ] )
		@budget.destroy

		redirect_to budgets_path
	end

	private
		def budget_params
			params.require( :budget )
				.permit( :title )
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

	def new
		@budget = Budget.find( params[ :budget_id ] )
		@expense = @budget.expenses.build
	end

	def create
		@budget = Budget.find( params[ :budget_id ] )
		@expense = @budget.expenses.build( expense_params )

		if @expense.save
			redirect_to budget_path( @budget )
		else
			render 'new'
		end
	end

	def destroy
		@budget = Budget.find( params[ :budget_id ] )
		@expense = @budget.expenses.find( params[ :id ] )
		@expense.destroy
		redirect_to budget_path( @budget )
	end

	private
		def expense_params
			params.require( :expense )
				.permit( :title, :value, :category )
		end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController

	def new
		@budget = Budget.find( params[ :budget_id ] )
		@income = @budget.incomes.build
	end

	def create
		@budget = Budget.find( params[ :budget_id ] )
		@income = @budget.incomes.build( income_params )

		if @income.save
			redirect_to budget_path( @budget )
		else
			render 'new'
		end
	end

	def destroy
		@budget = Budget.find( params[ :budget_id ] )
		@income = @budget.incomes.find( params[ :id ] )
		@income.destroy
		redirect_to budget_path( @budget )
	end

	private
		def income_params
			params.require( :income )
				.permit( :title, :value )
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article), method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/budgets/edit.html.erb
<h1>Editing budget</h1>
 
<%= form_for :budget, url: budget_path(@budget), method: :patch do |f| %>
 
  <% if @budget.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@budget.errors.count, "error") %> prohibited
        this budget from being saved:
      </h2>
      <ul>
        <% @budget.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<h1>Budgets</h1>

<%= link_to 'New budget', new_budget_path %>

<table>
  <tr>
    <th>Title</th>
    <th colspan="3"></th>
  </tr>
 
  <% @budgets.each do |budget| %>
    <tr>
      <td><%= budget.title %></td>
      <td><%= link_to 'Show', budget_path(budget) %></td>
      <td><%= link_to 'Edit', edit_budget_path(budget) %></td>
      <td><%= link_to 'Delete', budget_path(budget), method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/budgets/new.html.erb
<%= form_for :budget, url: budgets_path do |f| %>

  <% if @budget.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@budget.errors.count, "error") %> prohibited
        this budget from being saved:
      </h2>
      <ul>
        <% @budget.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', budgets_path %>

app/views/budgets/show.html.erb
<p>
  <%= @budget.title %>
</p>
<p>
	Balance <%= @budget.incomes.sum( :value ) - @budget.expenses.sum( :value ) %>
</p>
<p>
<%= link_to 'Edit', edit_budget_path(@budget) %> |
<%= link_to 'Back', budgets_path %>
</p>

<%= link_to 'New Income', new_budget_income_path( @budget ) %>
<table>
<tr>
	<th>Income</th>
	<th>Value</th>
</tr>
<%= render @budget.incomes %>
<tr>
	<td>Total</td>
	<td><%= @budget.incomes.sum( :value ) %></td>
</tr>
</table>

<%= link_to 'New Expense', new_budget_expense_path( @budget ) %>
<table>
<tr>
	<th>Expense</th>
	<th>Value</th>
	<th>Category</th>
</tr>
<%= render @budget.expenses %>
<tr>
	<td>Total</td>
	<td><%= @budget.expenses.sum( :value ) %></td>
</tr>
</table>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/expenses/_expense.html.erb
<tr>
	<td><%= expense.title %></td>
	<td><%= expense.value %></td>
	<td><%= expense.category %></td>
	<td><%= link_to 'Delete', [ expense.budget, expense ], method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/expenses/new.html.erb
<%= form_for :expense, url: budget_expenses_path do |f| %>

  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@expense.errors.count, "error") %> prohibited
        this expense from being saved:
      </h2>
      <ul>
        <% @expense.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </p>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', budgets_path %>

app/views/incomes/_income.html.erb
<tr>
	<td><%= income.title %></td>
	<td><%= income.value %></td>
	<td><%= link_to 'Delete', [ income.budget, income ], method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/incomes/new.html.erb
<%= form_for :income, url: budget_incomes_path do |f| %>

  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@income.errors.count, "error") %> prohibited
        this income from being saved:
      </h2>
      <ul>
        <% @income.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', budgets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>